name: tenor_client
description: Tenor client for GIFs
version: 0.1.2


environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  dio: ^5.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
